services:
  jupyter:
    image: jupyter/base-notebook:latest
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "docker"